struct Constanten {
    
    // tabelnamen
    static let TABLE_VAKANTIE: String = "Vakantie"
    static let TABLE_AFBEELDING: String = "Afbeelding"
    static let TABLE_CONTACTPERSOON: String = "Contactpersoon"
    static let TABLE_DEELNEMER: String = "Deelnemer"
    static let TABLE_FAVORIET: String = "Favoriet"
    static let TABLE_FEEDBACK: String = "Feedback"
    static let TABLE_INSCHRIJVINGVAKANTIE: String = "InschrijvingVakantie"
    static let TABLE_INSCHRIJVINGVORMING: String = "InschrijvingVorming"
    static let TABLE_MONITOR: String = "Monitor"
    static let TABLE_OUDER: String = "Ouder"
    static let TABLE_VOORKEUR: String = "Voorkeur"
    static let TABLE_VORMING: String = "Vorming"
    static let TABLE_USER: String = "User"
    
    // kolomnaam
    static let COLUMN_OBJECTID: String = "objectId"
    static let COLUMN_AFBEELDING: String = "afbeelding"
    static let COLUMN_VAKANTIE: String = "vakantie"
    static let COLUMN_GSM: String = "gsm"
    static let COLUMN_NAAM: String = "naam"
    static let COLUMN_TELEFOON: String = "telefoon"
    static let COLUMN_VOORNAAM: String = "voornaam"
    static let COLUMN_BUS: String = "bus"
    static let COLUMN_GEBOORTEDATUM: String = "geboortedatum"
    static let COLUMN_GEMEENTE: String = "gemeente"
    static let COLUMN_NUMMER: String = "nummer"
    static let COLUMN_POSTCODE: String = "postcode"
    static let COLUMN_STRAAT: String = "straat"
    static let COLUMN_GEBRUIKER: String = "gebruiker"
    static let COLUMN_DATUM: String = "datum"
    static let COLUMN_GOEDGEKEURD: String = "goedgekeurd"
    static let COLUMN_WAARDERING: String = "waardering"
    static let COLUMN_SCORE: String = "score"
    static let COLUMN_CONTACTPERSOON1: String = "contactpersoon1"
    static let COLUMN_CONTACTPERSOON2: String = "contactpersoon2"
    static let COLUMN_DEELNEMER: String = "deelnemer"
    static let COLUMN_EXTRAINFORMATIE: String = "extraInformatie"
    static let COLUMN_OUDER: String = "ouder"
    static let COLUMN_MONITOR: String = "monitor"
    static let COLUMN_VORMING: String = "vorming"
    static let COLUMN_PERIODE: String = "periode"
    static let COLUMN_AANSLUITINGSNUMMER: String = "aansluitingsNr"
    static let COLUMN_AANSLUITINGSNUMMERTWEEDEOUDER: String = "aansluitingsNrTweedeOuder"
    static let COLUMN_LIDNUMMER: String = "lidnummer"
    static let COLUMN_CODEGERECHTIGDE: String = "codeGerechtigde"
    static let COLUMN_EMAIL: String = "email"
    static let COLUMN_RIJKSREGISTERNUMMER: String = "rijksregisterNr"
    static let COLUMN_TITEL: String = "titel"
    static let COLUMN_VERTREKDATUM: String = "vertrekdatum"
    static let COLUMN_TERUGKEERDATUM: String = "terugkeerdatum"
    static let COLUMN_AANTALDAGENNACHTEN: String = "aantalDagenNachten"
    static let COLUMN_BASISPRIJS: String = "basisPrijs"
    static let COLUMN_BONDMOYSONLEDENPRIJS: String = "bondMoysonLedenPrijs"
    static let COLUMN_MINLEEFTIJD: String = "minLeeftijd"
    static let COLUMN_MAXLEEFTIJD: String = "maxLeeftijd"
    static let COLUMN_FORMULE: String = "formule"
    static let COLUMN_INBEGREPENPRIJS: String = "inbegrepenPrijs"
    static let COLUMN_KORTEBESCHRIJVING: String = "korteBeschrijving"
    static let COLUMN_LOCATIE: String = "locatie"
    static let COLUMN_MAXAANTALDEELNEMERS: String = "maxAantalDeelnemers"
    static let COLUMN_STERPRIJS1OUDER: String = "sterPrijs1ouder"
    static let COLUMN_STERPRIJS2OUDERS: String = "sterPrijs2ouders"
    static let COLUMN_VERVOERWIJZE: String = "vervoerwijze"
    static let COLUMN_LINK: String = "link"
    static let COLUMN_BETALINGSWIJZE: String = "betalingswijze"
    static let COLUMN_CRITERIADEELNEMERS: String = "criteriaDeelnemers"
    static let COLUMN_INBEGREPENINPRIJS: String = "inbegrepenInPrijs"
    static let COLUMN_PERIODES: String = "periodes"
    static let COLUMN_PRIJS: String = "prijs"
    static let COLUMN_TIPS: String = "tips"
    static let COLUMN_WEBSITELOCATIE: String = "websiteLocatie"
    
    // constraints
    static let CONSTRAINT_EQUALTO: String = "equalTo"
    static let CONSTRAINT_NOTCONTAINEDIN: String = "notContainedIn"
    static let CONSTRAINT_NOTEQUALTO: String = "notEqualTo"
    static let CONSTRAINT_CONTAINEDIN: String = "containedIn"
}